import { db } from './firebase';
import { doc, getDoc } from 'firebase/firestore';
import { formatCurrency, cleanPhoneNumber } from './utils';

export const sendWhatsAppNotification = async (transaction: any, customerName: string) => {
  try {
    const settingsSnap = await getDoc(doc(db, 'settings', 'notifications'));
    if (!settingsSnap.exists()) return null;
    
    const settings = settingsSnap.data();
    if (!settings.enabled || !settings.number) return null;

    const cleanedNumber = cleanPhoneNumber(settings.number);
    if (!cleanedNumber) return null;

    const message = `*CashFlow Alert* 🏦\n\n` +
      `*Customer:* ${customerName}\n` +
      `*Type:* ${transaction.type === 'in' ? '🟢 CASH IN' : '🔴 CASH OUT'}\n` +
      `*Amount:* ${formatCurrency(transaction.amount)}\n` +
      `*Category:* ${transaction.category || 'N/A'}\n` +
      `*Date:* ${transaction.date}\n` +
      `*Description:* ${transaction.description || 'N/A'}\n\n` +
      `_Generated by CashFlow Manager_`;

    const encodedMessage = encodeURIComponent(message);
    const whatsappUrl = `https://wa.me/${cleanedNumber}?text=${encodedMessage}`;
    
    return whatsappUrl;
  } catch (error) {
    console.error("WhatsApp notification error:", error);
    return null;
  }
};
